[build]
  publish = "."

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200
  force = true

[[redirects]]
  from = "/api/shazam"
  to = "/.netlify/functions/shazam"
  status = 200
  force = true

[[redirects]]
  from = "/api/image"
  to = "/.netlify/functions/image"
  status = 200
  force = true
